name: Thank new issues

on:
  issues:
    types: [opened]

jobs:
  thank-you:
    runs-on: ubuntu-latest
    steps:
      - name: Thank the user
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.payload.issue.number;
            const user = context.payload.issue.user.login;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: `Hi @${user}, thanks for opening an issue! We really appreciate your contribution. 🚀`
            });
